CustomToDo.Web/Areas/Contributor/Models/TaskModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CustomToDo.Web.Models
{
    public class TaskModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Priority { get; set; }
        public int Status { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public int Creator { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int ParentId { get; set; }
        public int SubTaskCount { get; set; }
        public List<TaskModel> SubTaskList { get; set; }
        public int taskCount { get; set; }


    }

    public class TaskPageModel
    {
        public List<TaskModel> PageTasks { get; set; }
        public List<TaskModel> TotalTasks { get; set; }
    }
}

CustomToDo.Web/Areas/Contributor/Models/UploadedFile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CustomToDo.Web.Areas.Contributor.Models
{
    public class UploadedFile
    {
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }
        public int FileSize { get; set; }

        public string FileExtension { get; set; }
    }
}

CustomToDo.Web/Areas/Contributor/Controllers/ContributorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CustomToDo.BAL.Repository;
using CustomToDo.DAL;
using CustomToDo.Web.Areas.Contributor.Models;
using CustomToDo.Web.HelperClass;
using CustomToDo.Web.Models;


namespace CustomToDo.Web.Areas.Contributor.Controllers
{
    public class ContributorController : Controller
    {
        public ITask _task;
        public IAppUser _appUser;
        public ITaskAttachment _taskAttachment;

        public ContributorController(ITask task, IAppUser appUser, ITaskAttachment taskAttachment)
        {
            _task = task;
            _appUser = appUser;
            _taskAttachment = taskAttachment;
        }

        // GET: Contributor/Contributor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MyDay(string sortOrder)
        {
            ViewBag.sortImportant = String.IsNullOrEmpty(sortOrder) ? "imp_desc" : "";
            ViewBag.sortDue = String.IsNullOrEmpty(sortOrder) ? "duedate_desc" : "";
            ViewBag.sortComplete = String.IsNullOrEmpty(sortOrder) ? "complete_desc" : "";
            ViewBag.sortMyday = String.IsNullOrEmpty(sortOrder) ? "myday_desc" : "";
            ViewBag.sortAlpha = String.IsNullOrEmpty(sortOrder) ? "alpha_desc" : "";
            ViewBag.sortCreate = String.IsNullOrEmpty(sortOrder) ? "create_desc" : "";

            TaskPageModel model = new TaskPageModel();

            #region Page Tasks
            List<TaskModel> list = new List<TaskModel>();
            var gettasklists = _task.GetAll().Where(x => x.DueDate == DateTime.Today && x.IsDeleted == false && x.ParentId == null).ToList();
            foreach(var gettask in gettasklists)
            {
                TaskModel task = new TaskModel();
                task.Id = gettask.Id;
                task.Title = gettask.Title;
                task.Priority = gettask.Priority;
                task.Status = gettask.Status;
                task.AssignedTo = gettask.AssignedTo;
                task.CreatedOn = gettask.CreatedOn;
                task.Creator = gettask.Creator;
                task.LastModifiedOn = gettask.LastModifiedOn;
                task.UpdatedBy = gettask.UpdatedBy;
                task.DueDate = gettask.DueDate;
                task.Comments = gettask.Comments;
                task.ParentId = gettask.ParentId ?? 0;

                var subtasklist = _task.GetAll().Where(x => x.DueDate > DateTime.Today && x.IsDeleted == false && x.ParentId == gettask.Id).ToList();
                List<TaskModel> sublist = new List<TaskModel>();
                foreach(var getsubtask in subtasklist)
                {
                    TaskModel subtask = new TaskModel();
                    subtask.Id = getsubtask.Id;
                    subtask.Title = getsubtask.Title;
                    subtask.Priority = getsubtask.Priority;
                    subtask.Status = getsubtask.Status;
                    subtask.AssignedTo = getsubtask.AssignedTo;
                    subtask.CreatedOn = getsubtask.CreatedOn;
                    subtask.Creator = getsubtask.Creator;
                    subtask.LastModifiedOn = getsubtask.LastModifiedOn;
                    subtask.UpdatedBy = getsubtask.UpdatedBy;
                    subtask.DueDate = getsubtask.DueDate;
                    subtask.Comments = getsubtask.Comments;
                    sublist.Add(subtask);
                }
                task.SubTaskList = sublist;

                list.Add(task);
            }


            foreach(var listitem in list)
            {
                listitem.SubTaskCount = _task.GetAll().Where(l => l.IsDeleted == false && l.ParentId == listitem.Id).Count();
                listitem.taskCount = _task.GetAll().Where(l => l.IsDeleted == false && l.ParentId == listitem.Id && l.Status == (int)CustomToDoUtility.Statuses.close).Count();
            }

            switch(sortOrder)
            {
                case "imp_desc":
                    try
                    {
                        list = list.OrderByDescending(x => x.Priority).ToList();
                    }
                    catch(Exception ex) { }
                    break;
                case "duedate_desc":
                    try
                    {
                        list = list.OrderBy(x => x.DueDate).ToList();
                    }
                    catch(Exception ex)
                    {
                        Response.Write(ex);
                    }
                    break;
                case "complete_desc":
                    try
                    {
                        list = list.OrderByDescending(x => x.Status).ToList();
                    }
                    catch(Exception ex)
                    {
                        Response.Write(ex);
                    }
                    break;
                case "myday_desc":
                    try
                    {
                        list = list.OrderByDescending(x => x.DueDate).ThenBy(x => x.DueDate == DateTime.Today).ToList();
                    }
                    catch(Exception ex)
                    {
                        Response.Write(ex);
                    }
                    break;
                case "alpha_desc":
                    try
                    {
                        list = list.OrderBy(x => x.Title).ToList();
                    }
                    catch(Exception ex)
                    {
                        Response.Write(ex);
                    }
                    break;
                case "create_desc":
                    try
                    {
                        list = list.OrderBy(x => x.CreatedOn).ToList();
                    }
                    catch(Exception ex)
                    {
                        Response.Write(ex);
                    }
                    break;
                default:
                    break;
            }
            model.PageTasks = list;
            #endregion

            model.TotalTasks = _task.GetAll().Where(x => x.IsDeleted == false && x.ParentId == null).Select(x => new TaskModel()
            {
                Id = x.Id,
                Title = x.Title,
                Priority = x.Priority,
                Status = x.Status,
                AssignedTo = x.AssignedTo,
                CreatedOn = x.CreatedOn,
                Creator = x.Creator,
                LastModifiedOn = x.LastModifiedOn,
                UpdatedBy = x.UpdatedBy,
                DueDate = x.DueDate,
                Comments = x.Comments

            }).OrderByDescending(x => x.CreatedOn).ToList();

            return View(model);
        }

        public ActionResult Planned(string sortOrder)
        {
            ViewBag.sortImportant = String.IsNullOrEmpty(sortOrder) ? "imp_desc" : "";
            ViewBag.sortDue = String.IsNullOrEmpty(sortOrder) ? "duedate_desc" : "";
            ViewBag.sortComplete = String.IsNullOrEmpty(sortOrder) ? "complete_desc" : "";
            ViewBag.sortMyday = String.IsNullOrEmpty(sortOrder) ? "myday_desc" : "";
            ViewBag.sortAlpha = String.IsNullOrEmpty(sortOrder) ? "alpha_desc" : "";
            ViewBag.sortCreate = String.IsNullOrEmpty(sortOrder) ? "create_desc" : "";

            TaskPageModel model = new TaskPageModel();

            #region Page Tasks
            List<TaskModel> list = new List<TaskModel>();
            var gettasklists = _task.GetAll().Where(x => x.DueDate > DateTime.Today && x.ParentId == null && x.Status != (int)CustomToDoUtility.Statuses.close && x.IsDeleted == false).ToList();
            foreach(var gettask in gettasklists)
            {
                TaskModel task = new TaskModel();
                task.Id = gettask.Id;
                task.Title = gettask.Title;
                task.Priority = gettask.Priority;
                task.Status = gettask.Status;
                task.AssignedTo = gettask.AssignedTo;
                task.CreatedOn = gettask.CreatedOn;
                task.Creator = gettask.Creator;
                task.LastModifiedOn = gettask.LastModifiedOn;
                task.UpdatedBy = gettask.UpdatedBy;
                task.DueDate = gettask.DueDate;
                task.Comments = gettask.Comments;
                task.ParentId = gettask.ParentId ?? 0;

                var subtasklist = _task.GetAll().Where(x => x.DueDate > DateTime.Today && x.IsDeleted == false && x.ParentId == gettask.Id).ToList();
                List<TaskModel> sublist = new List<TaskModel>();
                foreach(var getsubtask in subtasklist)
                {
                    TaskModel subtask = new TaskModel();
                    subtask.Id = getsubtask.Id;
                    subtask.Title = getsubtask.Title;
                    subtask.Priority = getsubtask.Priority;
                    subtask.Status = getsubtask.Status;
                    subtask.AssignedTo = getsubtask.AssignedTo;
                    subtask.CreatedOn = getsubtask.CreatedOn;
                    subtask.Creator = getsubtask.Creator;
                    subtask.LastModifiedOn = getsubtask.LastModifiedOn;
                    subtask.UpdatedBy = getsubtask.UpdatedBy;
                    subtask.DueDate = getsubtask.DueDate;
                    subtask.Comments = getsubtask.Comments;
                    sublist.Add(subtask);
                }
                task.SubTaskList = sublist;

                list.Add(task);
            }

            foreach(var listitem in list)
            {
                listitem.SubTaskCount = _task.GetAll().Where(l => l.IsDeleted == false && l.ParentId == listitem.Id).Count();
                listitem.taskCount = _task.GetAll().Where(l => l.IsDeleted == false && l.ParentId == listitem.Id && l.Status == (int)CustomToDoUtility.Statuses.close).Count();
            }

            switch(sortOrder)
            {

CustomToDo.Web/Areas/Contributor/Views/Contributor/Assigned.cshtml
@model CustomToDo.Web.Models.TaskPageModel
@using CustomToDo.Web.HelperClass


@{
    ViewBag.Title = "Assigned";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="centerBackground">
    <div class="tasksToolbar with-subline">
        <div class="tasksToolbar-top">
            <div class="tasksToolbar-headline">
                <div class="tasksToolbar-titleContainer">
                    <div class="tasksToolbar-titleItem">
                        <h2 class="listTitle" tabindex="-1">
                            <span>Assigned to you</span>
                        </h2>
                    </div>
                </div>
            </div>
            <div class="taskToolbar-right">
                <div class="section">
                    <div class="section-item">
                        <div class="dropdown">
                            <button class="btn loadingButton btn section-innerClick toolbarButton dropdown-toggle" id="remind" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="glyphicon glyphicon-sort" aria-hidden="true"></i>
                                <span>Sort</span>
                            </button>
                            <div class="dropdown-menu">
                                <h6 class="dropdown-header">Sort by</h6>
                                <div class="dropdown-divider"></div>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-star-empty" aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Important", "Assigned", new { sortOrder = ViewBag.sortImportant })

                                            </div>
                                        </div>
                                    </div>
                                </button>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-calendar " aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Due date", "Assigned", new { sortOrder = ViewBag.sortDue })
                                            </div>
                                        </div>
                                    </div>
                                </button>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-tasks" aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Added to my day", "Assigned", new { sortOrder = ViewBag.sortMyday })
                                            </div>
                                        </div>
                                    </div>
                                </button>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-check" aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Completed", "Assigned", new { sortOrder = ViewBag.sortComplete })

                                            </div>
                                        </div>
                                    </div>
                                </button>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Alphabetically", "Assigned", new { sortOrder = ViewBag.sortAlpha })
                                            </div>
                                        </div>
                                    </div>
                                </button>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-calendar" aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Created on", "Assigned", new { sortOrder = ViewBag.sortCreate })
                                            </div>
                                        </div>
                                    </div>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="center-content">
        @Html.Partial("_CenterPageContent", Model)
    </div>

</div>

<script>
       
    var flag = 0;
   
    function checkForComplete(e) {

         var ischeck = $(e).is(":checked");
        var taskid = $(e).data('taskid');
        var ischecked = ischeck;
            $.ajax({
                url: '@Url.Action("Ischeck", "Contributor",new { area = "Contributor" })',
                type: "POST",
                data: { Id: taskid, ischecked: ischecked },
                datatype: "json",
                success: function (result) {
                    //location.reload();
                    $(".center-content").html(result);
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
    }

    $('.dropdown-toggle').dropdown()

    function MarkImportant(taskid) {
        
        $.ajax({
               url: '@Url.Action("IsImportant", "Contributor",new { area = "Contributor" })/' + taskid,
               type: "POST",
               data: { Id: taskid },
               datatype: "json",
            success: function (result) {
                   //location.reload();

                $(".center-content").html(result);
               },
            error: function (errormessage) {

                alert(errormessage.responseText);
               }
        });
    }

</script>

CustomToDo.Web/Areas/Contributor/Views/Contributor/Important.cshtml
@model CustomToDo.Web.Models.TaskPageModel
@using CustomToDo.Web.HelperClass

@{
    ViewBag.Title = "Important";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="centerBackground">
    <div class="tasksToolbar with-subline">
        <div class="tasksToolbar-top">
            <div class="tasksToolbar-headline">
                <div class="tasksToolbar-titleContainer">
                    <div class="tasksToolbar-titleItem">
                        <h2 class="listTitle" tabindex="-1">
                            <span>Important</span>
                        </h2>
                    </div>
                </div>
            </div>
            <div class="taskToolbar-right">
                <div class="section">
                    <div class="section-item">
                        <div class="dropdown">
                            <button class="btn loadingButton btn section-innerClick toolbarButton dropdown-toggle" id="remind" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="glyphicon glyphicon-sort" aria-hidden="true"></i>
                                <span>Sort</span>
                            </button>
                            <div class="dropdown-menu">
                                <h6 class="dropdown-header">Sort by</h6>
                                <div class="dropdown-divider"></div>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-star-empty" aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Important", "Important", new { sortOrder = ViewBag.sortImportant })
                                            </div>
                                        </div>
                                    </div>
                                </button>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-calendar " aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Due date", "Important", new { sortOrder = ViewBag.sortDue })
                                            </div>
                                        </div>
                                    </div>
                                </button>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-tasks" aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Added to my day", "Important", new { sortOrder = ViewBag.sortAlpha })
                                            </div>
                                        </div>
                                    </div>
                                </button>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-check" aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                Completed
                                            </div>
                                        </div>
                                    </div>
                                </button>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Alphabetically", "Important", new { sortOrder = ViewBag.sortAlpha })

                                            </div>
                                        </div>
                                    </div>
                                </button>
                                <button class="dropdown-item" type="button">
                                    <div class="section-inner">
                                        <div class="section-icon">
                                            <i class="glyphicon glyphicon-calendar" aria-hidden="true"></i>
                                        </div>
                                        <div class="section-content">
                                            <div class="section-title">
                                                @Html.ActionLink("Created  on", "Important", new { sortOrder = ViewBag.sortCreate })
                                            </div>
                                        </div>
                                    </div>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <span id="centerColumn">
        <div class="baseAdd addTask" style="width:100%">
            <div class="taskItem-body">
                <span class="glyphicon glyphicon-plus"></span>
                <input id="baseAddInput-addStep" class="baseAdd-input chromeless taskAdd " type="text" maxlength="255" placeholder="Add step" value="" style="margin-left:10px">
                <input type="button" id="Addbtn" class="btn-link addbtn" style="display:none" value="Add" />
            </div>
        </div>
    </span>

    <div class="center-content">
        @Html.Partial("_CenterPageContent", Model)
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.addbtn').unbind('click');
        $('.addbtn').bind('click', function () {
            var title = $('.taskAdd').val();
            var type = "Important";
            $.ajax({
                url: '@Url.Action("Addtask", "Contributor",new { area = "Contributor" })/',
                type: "POST",
                data: { title: title, type: type },
                datatype: "json",
                success: function (result) {
                    location.reload();
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
        });

        $('.taskAdd').bind('keyup', function () {
            var stepvalue = $(this).val();
            if (stepvalue.length > 0) {
                $('.addbtn').show();
            }
            else {
                $('.addbtn').hide();
            }
        });
    });

    var flag = 0;

    function checkForComplete(e) {

         var ischeck = $(e).is(":checked");
        var taskid = $(e).data('taskid');
        var ischecked = ischeck;
            $.ajax({
                url: '@Url.Action("Ischeck", "Contributor",new { area = "Contributor" })',
                type: "POST",
                data: { Id: taskid, ischecked: ischecked },
                datatype: "json",
                success: function (result) {
                    //location.reload();
                    $(".center-content").html(result);
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
    }

    $('.dropdown-toggle').dropdown()

    function MarkImportant(taskid) {

        $.ajax({
               url: '@Url.Action("IsImportant", "Contributor",new { area = "Contributor" })/' + taskid,
               type: "POST",
               data: { Id: taskid },
               datatype: "json",
            success: function (result) {
                   //location.reload();

                $(".center-content").html(result);
               },
            error: function (errormessage) {

                alert(errormessage.responseText);
               }
        });
    }


</script>

CustomToDo.Web/Areas/Contributor/Views/Contributor/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

CustomToDo.Web/Areas/Contributor/Views/Contributor/_AttachmentData.cshtml
@using CustomToDo.DAL
@model IEnumerable<TaskAttachment>

@if (Model.Count() > 0)
{
    foreach (var result in Model)
    {
        <div class="divAttachment" style="width: 100%;" data-id="@result.Id">
            <div style="width: 90%; float: left;">
                <a class="link section-item file-item" rel="noreferrer" href="@result.FilePath" target="_blank">
                    <div class="thumbnail-wrapper">
                        <div class="thumbnail">@result.FileExtension.ToUpper()</div>
                    </div>
                    <div class="file-content">

                        <div class="file-title">@result.FileName</div>
                        @{
                            var fileSize = string.Empty;

                            if (result.FileSize != null)
                            {
                                if (result.FileSize > 1048576)
                                {
                                    decimal size = result.FileSize.Value * 100 / 1048576;
                                    var calculatedSize = Math.Round(size) / 100;
                                    fileSize = calculatedSize.ToString() + " MB";
                                }
                                else if (result.FileSize > 1024)
                                {
                                    decimal size = result.FileSize.Value * 100 / 1024;
                                    var calculatedSize = Math.Round(size) / 100;
                                    fileSize = calculatedSize.ToString() + " KB";
                                }
                                else
                                {
                                    fileSize = result.FileSize.Value.ToString() + " Bytes";
                                }
                            }
                        }

                        <div class="file-metadata"><span>@fileSize</span></div>
                    </div>
                </a>
            </div>
            <div style="width: 10%; float: left; padding-top: 30px;">
                <i class="removeAttachment"><span class="glyphicon glyphicon-remove"></span></i>
            </div>
            <div class="clearfix"></div>
        </div>
    }
}

<script>

</script>