CustomToDo.Web/Controllers/LoginController.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CustomToDo.BAL.Repository;
using CustomToDo.Web.HelperClass;
using CustomToDo.Web.Models;

namespace CustomToDo.Web.Controllers
{
    public class LoginController : Controller
    {
        public IEmp _empServices;
        public IAppUser _appUser;


        public LoginController(IEmp empServices,IAppUser user)
        {
            _empServices = empServices;
            _appUser = user;
        }

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public JsonResult LoginCheck(string username, string password)
        {
            DAL.AppUser appuser;

            appuser = _appUser.FindBy(x => x.Username == username && x.Password == password).FirstOrDefault();
            if (appuser != null)
            {
                if (appuser.RoleId == (int)CustomToDoUtility.Role.Admin)
                {
                    Session["CurrentUser"] = appuser;
                    return Json("Admin");
                }
                else if (appuser.RoleId == (int)CustomToDoUtility.Role.Manager)
                {
                    Session["CurrentUser"] = appuser;
                    return Json("Manager");
                }
                else if (appuser.RoleId == (int)CustomToDoUtility.Role.Contributor)
                {
                    Session["CurrentUser"] = appuser;
                    return Json("Contributor");
                }
                else
                {
                    return Json("fail");
                }
            }
            else
            {
                return Json("fail");
            }
            }

        }
    }

CustomToDo.Web/Views/Shared/Login_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" type="text/javascript"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/Style.css">

    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("To Do","","",new { area = "" },new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <hr />

   
        <!-- Page Content Holder -->
        <div id="content">
            <div class="container-fluid">
                <div class="container body-content">
                    @RenderBody()
                    <hr />
                    <footer>
                        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                    </footer>
                </div>
            </div>
        </div>
    
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts",required: false)
</body>
</html>

CustomToDo.Web/Views/Shared/_Layout.cshtml
@model CustomToDo.Web.Models.TaskPageModel
@using CustomToDo.Web.HelperClass
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" type="text/javascript"></script>
    @*<script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js" type="text/javascript"></script>*@
    <script src="~/Scripts/dashboard/sb-admin.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
    <link rel="stylesheet" href="//cdn.materialdesignicons.com/5.0.45/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/Style.css">
    <link rel="stylesheet" type="text/css" href="~/Content/SidePanel.css">
    <link rel="stylesheet" type="text/css" href="~/Content/dashboard/sb_admin.css">
    <link rel="stylesheet" type="text/css" href="~/Content/dashboard/dashboard_style.css">
    <script src="~/Content/dashboard/vendor/jquery-easing/jquery.easing.min.js"></script>



    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script language="javascript" type="text/javascript">
        $(document).ready(function ($) {
            $.ajaxSetup({
                cache: false,
                statusCode: {
                    401: function (jqxhr, textStatus, errorThrown) { window.location.reload(); }
                }
            });
            $(document)
                .ajaxStart(function () { $("#ajax-loader").show(); })
                .ajaxStop(function () { $("#ajax-loader").hide(); });
        });
    </script>
</head>
<body id="page-top">

    @{
        var currentUser = CustomToDoUtility.CurrentLoginUser;
        if (currentUser == null)
        {
            Response.Redirect("~/Login/Login");
        }

    }

    <div class="navbar navbar-inverse navbar-fixed-top ">

        <div class="container">

            <div class="navbar-header">
                @Html.ActionLink("To Do", "Task", "Contributor", new { area = "Contributor" }, new { @class = "navbar-brand" })

                @Html.ActionLink("Logout", "Login", "Login", new { area = "" }, new { @class = "navbar-brand navbar-right" })

            </div>
        </div>
    </div>
    <div id="ajax-loader"></div>
    <hr />

    <div class="wrapper">
        <!-- Sidebar Holder -->

        <div class="menubar">
            @Html.Partial("_MenuBar", Model)

        </div>

        <!-- Page Content Holder -->
        <div id="content">
            <div class="container">

                <div id="divBody" class="container body-content">
                    @RenderBody()

                    <footer>
                        <p>&copy; @DateTime.Now.Year </p>
                    </footer>
                </div>
            </div>
        </div>

    </div>
    @*<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>*@
    @*<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>*@


    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebarToggle").on('click', function (e) {
                //e.preventDefault();
                $("body").toggleClass("sidebar-toggled");
                $(".sidebar").toggleClass("toggled");
            });
            $("ul.list-unstyled > li").click(function () {
                $(this).toggleClass('toggled');

            });

        });
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CustomToDo.Web/Views/Shared/_MenuBar.cshtml
@model CustomToDo.Web.Models.TaskPageModel
@using CustomToDo.Web.HelperClass
    <div class="sidebar">
        <button type="button" id="sidebarToggle" class="btn btn-info navbar-btn">
            @* <i class="glyphicon glyphicon-align-center"></i>*@
            <img src="~/Images/logo.png" class="logo" />
        </button>

        <ul class="list-unstyled components">
            <li>
                <a href='@Url.Action("MyDay","Contributor",new { area = "Contributor" })'>
                    <i class="glyphicon glyphicon-tasks"></i>
                    <span>My Day - </span>
                    <span>
                        @Model.TotalTasks.Count(m => m.DueDate == DateTime.Today)
                    </span>
                </a>
            </li>
            <li>
                <a href='@Url.Action("Important","Contributor",new { area = "Contributor" })'>
                    <i class="glyphicon glyphicon-star"></i>
                    <span>IMPORTANT - </span>
                    <span>
                        @Model.TotalTasks.Count(m => m.Priority == (int)CustomToDoUtility.Priorities.Important)
                    </span>
                </a>
            </li>
            <li>
                <a href='@Url.Action("Planned","Contributor",new { area = "Contributor" })'>
                    <i class="glyphicon glyphicon-calendar"></i>
                    <span>PLANNED - </span>
                    <span>
                        @Model.TotalTasks.Count(m => m.DueDate > DateTime.Today && m.Status != (int)CustomToDoUtility.Statuses.close)
                    </span>
                </a>
            </li>
            <li>
                <a href='@Url.Action("Assigned","Contributor",new { area = "Contributor" })'>
                    <i class="glyphicon glyphicon-link"></i>
                    <span>ASSIGNED TO YOU - </span>
                    <span>
                        @Model.TotalTasks.Count(m => m.AssignedTo.HasValue && m.AssignedTo.Value == CustomToDoUtility.CurrentLoginUser.Id)
                    </span>
                </a>
            </li>
            <li>
                <a href='@Url.Action("Task","Contributor",new { area = "Contributor" })'>
                    <i class="glyphicon glyphicon-home"></i>
                    <span>TASK - </span>
                    <span>
                        @Model.TotalTasks.Count()
                    </span>
                </a>
            </li>
        </ul>
    </div>